---
title: "coAuthor-ENA"
author: "Zach"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# Load packages
```{r message=F, warning=F, paged.print=T}

rm(list=ls()) #clear environment

library(rENA)
#library(ona)
#library(tma)
library(tidyverse) #for wrangling
library(lmerTest) #for hlms
library(ICC) #for testing clustering of observations
library(emmeans)  #for comparing subpopulations 
library(performance) #for regression diagnostics

```

# Read data
```{r}
data1 <- read.csv('ena_update_2.csv',stringsAsFactors = FALSE)
glimpse(data1)
```


# Prep for ENA model
```{r }

units = data1[,c("session_id", 
                 "worker_id")]


conversation = data1[,c("session_id", 
                        "worker_id",
                        "sentSeq")]

codeCols = c(
  'compose', 
  #'delete', 
  'relocate',
  'reflect', 
  'seekSugg', 
  'acceptSugg', 
  'dismissSugg', 
  'lowModification',
  'highModification',
  'reviseSugg',
  'reviseUser'
)
  
codes = data1[,codeCols]

#mask = 

meta = data1[,c("genre",
                "highTemp"
                )]

```

# Run ENA model
```{r}
#with pipes
set = 
  ena.accumulate.data(
  units = units,
  conversation = conversation,
  codes = codes,
  metadata = meta,
  #mask = mask,
  window.size.back = "inf" # each line in the conversation can connect back to the first line--allows for more fine-grained view of connections w/i convos
) %>%
  ena.make.set()
```


# View space
```{r}
network = as.matrix(set$line.weights)
mean_network = colMeans(network)

network_mult = 0

p = ena.plot(set,title = "Overall Mean Network") %>%
  ena.plot.network(mean_network * network_mult,colors = "black")

p$plot
```


# Mean networks
```{r}
creat_pts = as.matrix(set$points$genre$creative)
arg_pts = as.matrix(set$points$genre$argumentative)

creat_net = colMeans(as.matrix(set$line.weights$genre$creative))
arg_net = colMeans(as.matrix(set$line.weights$genre$argumentative))

plot_cr = ena.plot(set, scale.to = "network", title = "Creative")  %>%
       ena.plot.points(points = creat_pts, colors = c("blue"))  %>%
       ena.plot.group(point = creat_pts,
                      colors =c("blue"), confidence.interval = "none")  %>%
       ena.plot.network(network = creat_net,colors = c("blue") )


plot_arg = ena.plot(set, scale.to = "network", title = "Creative")  %>%
       ena.plot.points(points = arg_pts, colors = c("red"))  %>%
       ena.plot.group(point = arg_pts,
                      colors =c("red"), confidence.interval = "none")  %>%
       ena.plot.network(network = arg_net,colors = c("red") )

plot_cr$plot
plot_arg$plot

```


# Network subtraction
```{r }

net_mult = 2

plot_sub = ena.plot(set, scale.to = "network", title = "Creative vs Argumentative")  %>%
       ena.plot.group(point = creat_pts,
                      colors =c("blue"), confidence.interval = "none")  %>%
       ena.plot.group(point = arg_pts,
                      colors =c("red"), confidence.interval = "none") %>% 
       ena.plot.network(network = (creat_net - arg_net) * net_mult,colors = c("blue","red") )
plot_sub$plot
```


# Statistical tests

## Set up data
```{r}
#names(set$points)
reg_data = set$points[,c(1:7)]
#glimpse(reg_data)

table(reg_data$genre,reg_data$worker_id)


```

## Clustering of observations
```{r}
ICCest(worker_id,SVD1,reg_data) #CI contains zero; not significant

ICCest(worker_id,SVD2,reg_data) #CI contains zero; not significant

```


## Regression analysis

### SVD1
```{r}

mod1x = lm(SVD1 ~ genre*highTemp, data = reg_data) #interaction
summary(mod1x)

mod2x = lm(SVD1 ~ genre + highTemp, data = reg_data)
summary(mod2x)

mod3x = lm(SVD1 ~ genre, data = reg_data)
summary(mod3x)

mod4x = lm(SVD1 ~ highTemp, data = reg_data)
summary(mod4x)

```
No models are significant


### SVD2

No models are significant
```{r}

mod1y = lm(SVD2 ~ genre*highTemp, data = reg_data) #interaction
summary(mod1y)

mod2y = lm(SVD2 ~ genre + highTemp, data = reg_data)
summary(mod2y)

mod3y = lm(SVD2 ~ genre, data = reg_data)
summary(mod3y)

mod4y = lm(SVD2 ~ highTemp, data = reg_data)
summary(mod4y)

```
No models are significant